services:
  api-devsecops:
    build: .
    container_name: api-devsecops
    ports:
      - "3000:3000"
    # ...tes volumes
    env_file:
      - .env
    networks:
      - sonarnet

networks:
  sonarnet:
    external: true
