services:
  api-devsecops:
    build: .
    container_name: api-devsecops
    ports:
      - "3000:3000"
    # ...tes volumes
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Hjr7hBqrvsd91-abCD45!Hdtw@nwbyaKkTq2prjzvVX6P
    networks:
      - sonarnet

networks:
  sonarnet:
    external: true
